name: Cron Job - Every 5 Minutes

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Make HTTPS Request
        run: |
          curl -X GET https://search-dev.onrender.com/
